name = "small-recipe-799f"
main = "src/worker.ts"
compatibility_date = "2023-08-07"

[[d1_databases]]
binding = "DB"
database_name = "small-recipe-799f"
database_id = "3b27b46b-dc36-4270-bd2d-ead31c48d937"
migrations_dir = "drizzle"
